### PR TITLE
Company statistics added

### PR DESCRIPTION
**Pull request by UI-Jakob**
Added company-stats function to get all available statistics for a selected company.

### CODE REVIEW

**Comment by ArkeologeN** [comment]
@UI-Jakob I am accepting the pull request but if you could create the test as well please?

**Comment by UI-Jakob** [comment]
@ArkeologeN Sure I will fix the tests as well but could you push out the update on NPM so I can use it on what I am building?

**Comment by ArkeologeN** [comment]
Sure, I was ill so made it late. Just doing it now.

**Comment by ArkeologeN** [comment]
Published! :)

**Pull request merged**
